Add new Spec
obsidiansystems/nix-thunk pull request #26
Opened 2022-07-13 12:55 UTC by romefeller

Merge this to solved pinned diamond path problem

2022-07-13 13:17 UTC, madeline-os commented
What does that mean?

2022-07-18 15:46 UTC, madeline-os commented
This needs a changelog

2022-07-18 15:47 UTC, madeline-os requested changes
Just needs documentation and changelog

2022-07-18 15:47 UTC, madeline-os commented on src/Nix/Thunk.hs
> +gitHubThunkSpecV6 :: ThunkSpec
Needs haddocks explaining why this exists

2022-07-18 15:47 UTC, madeline-os commented on src/Nix/Thunk.hs
> +gitThunkSpecV6 :: ThunkSpec
Haddock

2022-07-18 16:49 UTC, plt-amy commented
@madeline-os tested by:

```
$ nix-thunk create https://github.com/plt-amy/1lab.git 1lab
$ cat 1lab/thunk.nix
# DO NOT HAND-EDIT THIS FILE
let fetch = { private ? false, fetchSubmodules ? false, owner, repo, rev, sha256, ... }:
  if !fetchSubmodules && !private then builtins.fetchTarball {
    url = "https://github.com/${owner}/${repo}/archive/${rev}.tar.gz"; inherit sha256;
  } else (builtins.fetchTarball {
  url = "https://github.com/NixOS/nixpkgs/archive/3aad50c30c826430b0270fcf8264c8c41b005403.tar.gz";
  sha256 = "0xwqsf08sywd23x0xvw4c4ghq0l28w2ki22h0bdn766i16z9q2gr";
}).fetchFromGitHub {
    inherit owner repo rev sha256 fetchSubmodules private;
  };
  json = builtins.fromJSON (builtins.readFile ./github.json);
in fetch json⏎
$ nix-thunk unpack 1lab
Cloning into './1lab-7dbbebbff4b4db50/.'...
HEAD is now at 6d51d2ea defn: start work on synthetic homotopy theory; n-truncations
✔ Fetched thunk 1lab
```

then poking around the files to make sure everything was in order, which it was.

2022-07-20 20:22 UTC, madeline-os approved these changes

2022-07-21 14:52 UTC, merged