Ignore user's git configuration when shelling out
obsidiansystems/nix-thunk pull request #43
Opened 2022-08-31 18:53 UTC by plt-amy

Prevents two classes of issues:

1. A thunk works because of the user's git configuration, but does not work when built with nix. This can happen with e.g. `url.*.insteadof` causing `nix-thunk` to be able to resolve the URL, but not the nix builder.
2. The user's git configuration might have settings that only become valid in a version of Git newer than the one we're using (ran into this personally which is what prompted this fix).

Reverts #35 since it's impossible for `branch.*.merge` to be set to a non-standard value when cloning thunks.

2022-09-01 03:15 UTC, madeline-os requested changes
Needs a changelog entry

2022-09-01 16:54 UTC, plt-amy commented
@madeline-os done, also added changelog for #42 which was missing

2022-09-02 18:30 UTC, madeline-os approved these changes

2022-09-02 18:30 UTC, merged

2022-09-02 18:30 UTC, madeline-os commented
Thanks!